spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/devdb
      username: postgres
      password: postgres

flyway:
  user: postgres
  password: postgres
  outOfOrder: true
  table: data_sync_schema_version
  baseline-on-migrate: true
  url: jdbc:postgresql://localhost:5432/devdb
  locations: db/migration/ddl,db/migration/seed

source-schemas: kurnool

destination-schemas: public

sync:
  info:
    - sourceTable: eg_boundary_type
      destinationTable: eg_boundary_type
      columns:
        - source: id
          destination: id
          type: Integer

        - source: name
          destination: name
          Type: String

    - sourceTable: eg_boundary
      destinationTable: eg_boundary
      columns:
        - source: id
          destination: id
          type: Integer

        - source: name
          destination: name
          type: String
